// mockData.js
export const packagesMock = [
  {
    _id: "693ba2dda4eb2c30f65305a7",
    packageTitle: "Phuket Adventure Package",
    route: "69367feb7ae357b5b630354a",
    countries: "69367feb7ae357b5b630354b",
    heroMedia: { fileUrl: "https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=1200&h=600&fit=crop" },
    cardMedia: { fileUrl: "https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=400&h=300&fit=crop" },
    gallery: [
      { fileUrl: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800&h=500&fit=crop" },
      { fileUrl: "https://images.unsplash.com/photo-1537956965359-7573183d1f57?w=800&h=500&fit=crop" },
    ],
    durationDays: 5,
    nights: 4,
    seatsTotal: 30,
    seatsBooked: 10,
    price: 75000,
    currency: "INR",
    highlights: ["beach", "snorkeling", "island hopping"],
    inclusions: ["flight tickets", "hotel stay", "breakfast"],
    exclusions: ["visa fees", "personal expenses"],
    notes: ["carry ID proof", "travel insurance recommended"],
    locations: "Phuket, Phi Phi Island, James Bond Island",
    overview: "Experience the tropical paradise of Phuket with pristine beaches, crystal-clear waters, and vibrant culture. This carefully curated 5-day adventure combines relaxation with thrilling water sports and cultural exploration.",
    pickup: "Phuket International Airport",
    drop: "Phuket International Airport",
    meetingPoint: "Main Terminal - Arrival Hall",
    travelEssentials: {
      mustCarry: ["passport", "ID card", "sunscreen"],
      gears: ["camera", "snorkeling gear"],
      clothes: ["light clothes", "swimwear"],
      footwear: ["sandals", "water shoes"],
      medication: ["first aid kit", "prescription medicines"],
      personalAccessories: ["hat", "sunglasses"],
    },
    itinerary: [
      {
        dayTitle: "Arrival at Phuket",
        activities: ["Check-in hotel", "Evening beach walk", "Welcome dinner"],
      },
      {
        dayTitle: "Island Hopping",
        activities: ["Boat tour", "Snorkeling", "Lunch on island"],
      },
    ],
    ageLimit: { min: 12, max: 60 },
    isActive: true,
    isPublished: true,
    seo: {
      slug: "phuket-adventure-package",
      metaTitle: "Phuket Adventure Package",
      metaDescription: "Exciting 5N-6D Phuket tour with beach, snorkeling and island hopping",
      keywords: ["phuket", "adventure", "tour"],
    },
    createdBy: "69367feb7ae357b5b630354c",
    createdAt: "2025-12-12T05:06:37.738Z",
    updatedAt: "2025-12-12T05:06:37.785Z",
  },
];